### PR TITLE
Removed the random factor setting max queued songs by user

### PR DESCRIPTION
**Pull request by NachoKiman**

### CODE REVIEW

**Comment by juliangalati** [comment]
The only way this PR will be accepted is if the ctitizens could take a vote on it. Meanwhile randomness is closest to democracy's true form.

**Comment by NachoKiman** [comment]
> The only way this PR will be accepted is if the ctitizens could take a vote on it. Meanwhile randomness is closest to democracy's true form.
> If you really want it to be merged, at least add the possibility to choose between admin dictatorship and randomness.

This was a team decition, randomness is not "the closest to democracy", it is just annoying. The current functionality is, the population debate a settle in a correct number of songs to be able to add to the queue, and they configure the server. In future version this could be changed in runtime, but is not really a high priority feature.

**Comment by juliangalati** [comment]
Mmm, what I'm saying is, just don't delete the existing functionality. Add an "if" so you could decide which one you prefer.

**Comment by NachoKiman** [comment]
> Mmm, what I'm saying is, just don't delete the existing functionality. Add an "if" so you could decide which one you prefer.

The existing functionality makes no sense and will not be allowed or improved. It should be replaced by a new and better functionality that better reflects the democratic style we are going for.

**Pull request merged**
